version: '2'

services:

  elasticsearch:
    image: elasticsearch:2
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  django:
    image: scieloorg/opac_ssm
    user: django
    restart: always
    depends_on:
      - postgres
      - redis
      - elasticsearch
    command: /gunicorn.sh
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_SECRET_KEY=sdal#^4pih^ekewqtq8k_m9lin#136olq-_p086wsu-)=8=ns!
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=True
      - USE_DOCKER=yes
      - HAYSTACK_CONNECTIONS_HOST=elasticsearch
      - HAYSTACK_CONNECTIONS_PORT=9200
      - HAYSTACK_CONNECTIONS_INDEX=opac_ssm_idx
    volumes:
      - /etc/localtime:/etc/localtime:ro

  redis:
    image: redis:latest
    user: redis
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro

  celeryworker:
    image: scieloorg/opac_ssm
    user: django
    restart: always
    depends_on:
      - postgres
      - redis
      - elasticsearch
    command: celery -A opac_ssm.taskapp worker -l INFO
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_SECRET_KEY=sdal#^4pih^ekewqtq8k_m9lin#136olq-_p086wsu-)=8=ns!
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=False
      - USE_DOCKER=yes
      - HAYSTACK_CONNECTIONS_HOST=elasticsearch
      - HAYSTACK_CONNECTIONS_PORT=9200
      - HAYSTACK_CONNECTIONS_INDEX=opac_ssm_idx
    volumes:
      - /etc/localtime:/etc/localtime:ro

  celerybeat:
    image: scieloorg/opac_ssm
    user: django
    restart: always
    depends_on:
      - postgres
      - redis
      - elasticsearch
    command: celery -A opac_ssm.taskapp beat -l INFO
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_SECRET_KEY=sdal#^4pih^ekewqtq8k_m9lin#136olq-_p086wsu-)=8=ns!
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=False
      - USE_DOCKER=yes
      - HAYSTACK_CONNECTIONS_HOST=elasticsearch
      - HAYSTACK_CONNECTIONS_PORT=9200
      - HAYSTACK_CONNECTIONS_INDEX=opac_ssm_idx
    volumes:
      - /etc/localtime:/etc/localtime:ro

  grpc:
    image: scieloorg/opac_ssm
    user: django
    restart: always
    depends_on:
      - postgres
      - redis
      - elasticsearch
    command: /start-grpc.sh
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DJANGO_SECRET_KEY=sdal#^4pih^ekewqtq8k_m9lin#136olq-_p086wsu-)=8=ns!
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=False
      - USE_DOCKER=yes
      - HAYSTACK_CONNECTIONS_HOST=elasticsearch
      - HAYSTACK_CONNECTIONS_PORT=9200
      - HAYSTACK_CONNECTIONS_INDEX=opac_ssm_idx_dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5000:5000"
